version: 1.0.{build}
image: Ubuntu2004

install:
  - curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
  - sudo apt-get update
  - sudo apt-get install -y nodejs
  - npm install -g yarn
  - yarn install --frozen-lockfile

build: off

test_script:
  - yarn lint
  - yarn test
  - yarn test:e2e:headless
